<?php
// for each language:
// [0] => ISO 639-1 language code
// [1] => WordPress locale
// [2] => name
// [3] => not set for ltr scripts, 'rtl' otherwise
$languages = array(
	array('ar', 'ar', 'العربية', 'rtl'),
	array('bg', 'bg_BG', 'български'),
	array('bs', 'bs_BA', 'Bosanski'),
	array('ca', 'ca', 'Català'),
	array('cs', 'cs_CZ', 'Čeština'),
	array('cy', 'cy', 'Cymraeg'),
	array('da', 'da_DK', 'Dansk'),
	array('de', 'de_DE', 'Deutsch'),
	array('el', 'el', 'Ελληνικά'),
	array('en', 'en_CA', 'English'),
	array('en', 'en_US', 'English'),
	array('eo', 'eo', 'Esperanto'),
	array('es', 'es_CL', 'Español'),
	array('es', 'es_ES', 'Español'),
	array('es', 'es_PE', 'Español'),
	array('et', 'et', 'Eesti'),
	array('fa', 'fa_IR', 'فارسی', 'rtl'),
	array('fi', 'fi', 'Suomi'),
	array('fo', 'fo', 'Føroyskt'),
	array('fr', 'fr_FR', 'Français'),
	array('fy', 'fy', 'Frysk'),
	array('gl', 'gl_ES', 'Galego'),
	array('he', 'he_IL', 'עברית', 'rtl'),
	array('hr', 'hr', 'Hrvatski'),
	array('hu', 'hu_HU', 'Magyar'),
	array('id', 'id_ID', 'Bahasa Indonesia'),
	array('it', 'it_IT', 'Italiano'),
	array('ja', 'ja', '日本語'),
	array('jv', 'jv_ID', 'Basa Jawa'),
	array('ka', 'ka_GE', 'ქართული'),
	array('ko', 'ko_KR', '한국어'),
	array('ku', 'ckb', 'کوردی', 'rtl'),
	array('lv', 'lv', 'Latviešu valoda'),
	array('mk', 'mk_MK', 'македонски јазик'),
	array('my', 'my_MM', 'ဗမာစာ'),
	array('nb', 'nb_NO', 'Norsk Bokmål'),
	array('nl', 'nl_NL', 'Nederlands'),
	array('pl', 'pl_PL', 'Polski'),
	array('pt', 'pt_BR', 'Português'),
	array('pt', 'pt_PT', 'Português'),
	array('ro', 'ro_RO', 'Română'),
	array('ru', 'ru_RU', 'Русский'),
	array('si', 'si_LK', 'සිංහල'),
	array('sk', 'sk_SK', 'Slovenčina'),
	array('sl', 'sl_SI', 'Slovenščina'),
	array('sq', 'sq', 'Shqip'),
	array('sr', 'sr_RS', 'Српски језик'),
	array('sv', 'sv_SE', 'Svenska'),
	array('ta', 'ta_LK', 'தமிழ்'),
	array('th', 'th', 'ไทย'),
	array('tr', 'tr_TR', 'Türkçe'),
	array('ug', 'ug_CN', 'Uyƣurqə'),
	array('uk', 'uk', 'Українська'),
	array('zh', 'zh_CN', '中文'),
	array('zh', 'zh_TW', '台灣'),
);
?>
